"use client"

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Language = 'en' | 'de' | 'es'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    home: 'HOME',
    products: 'PRODUCTS',
    services: 'SERVICES',
    clients: 'CLIENTS',
    blog: 'BLOG',
    about: 'ABOUT US',
    contact: 'CONTACT',
    talkToExpert: 'CONTACT US',
    manufacturingBadge: 'Your Manufacturing Partner',
    manufacturingTitleStart: 'Are You Seeking a Trusted Partner in the Garment Industry for Your',
    manufacturingTitleHighlight: 'Perfect Clothing Manufacturing?',
    manufacturingDesc1Start: 'With countless garment producers in the market, finding the right partner can be overwhelming and exhausting.',
    manufacturingDesc1Highlight: 'But your search ends here!',
    manufacturingDesc1End: 'As one of the most reputable and established clothing manufacturing companies, we provide comprehensive solutions for all your garment production requirements.',
    manufacturingDesc2: 'As a pioneer of innovative fashion, we pride ourselves on being your ultimate manufacturing partner, ensuring your brand distinguishes itself in today\'s competitive marketplace through our premium garment manufacturing services. As a leading clothing manufacturer and exporter, we excel in delivering products that not only meet international quality standards but surpass expectations, guaranteeing your brand receives nothing less than exceptional excellence.',
    getQuote: 'GET A QUOTE',
    yearsExperience: 'Years Experience',
    countriesServed: 'Countries Served',
    customBadge: 'Custom Solutions',
    customTitleStart: 'Custom Clothing Manufacturers in Pakistan,',
    customTitleHighlight: 'Manufacturing Exclusive Clothing',
    customDesc1: 'If you are searching for a custom clothing manufacturer in Pakistan that can fulfill all your unique requirements? Your search ends here at Rijiz, where we deliver an extensive range of custom clothing solutions to transform your vision into reality. Unlike other bespoke apparel manufacturers, we provide complete custom clothing manufacturing services with limitless customization possibilities.',
    customDesc2Start: 'At Rijiz, we take pride in producing premium-quality clothing that aligns with your exact specifications. From screen printing and embroidery to digital printing,',
    customDesc2Link: 'private label clothing manufacturing',
    customDesc2End: ', cut and sew clothing production, and custom designing, we present a comprehensive array of customization services that are unparalleled in the industry.',
    customDesigns: 'Custom Designs',
    supportAvailable: 'Support Available',
    featuresBadge: 'Our Advantages',
    featuresTitleStart: 'Why Choose',
    featuresTitleHighlight: 'Axiom Rise',
    featuresTitleEnd: '?',
    featuresDesc: 'We combine traditional craftsmanship with cutting-edge technology to deliver exceptional clothing products that exceed expectations and set industry standards worldwide.',
    premiumQualityTitle: 'Premium Quality Assurance',
    premiumQualityDesc: 'Every garment undergoes rigorous multi-stage quality control processes with ISO 9001:2015 certification, ensuring international standards compliance and zero-defect delivery.',
    globalExportTitle: 'Global Export Network',
    globalExportDesc: 'Successfully exporting to 50+ countries across North America, Europe, Asia, and beyond with established logistics partnerships and customs expertise.',
    expertTeamTitle: 'Expert Manufacturing Team',
    expertTeamDesc: '5+ years of industry experience with skilled artisans and modern production facilities equipped with cutting-edge technology for precision manufacturing.',
    sustainableTitle: 'Sustainable & Ethical',
    sustainableDesc: 'OEKO-TEX certified eco-friendly materials with GOTS organic cotton options. BSCI compliant ethical labor practices and environmentally responsible production.',
    customDesignTitle: 'Custom Design Solutions',
    customDesignDesc: 'In-house design team offering complete customization from concept to production. Tech packs, sample development, and private label manufacturing services.',
    fastTurnaroundTitle: 'Fast Turnaround Time',
    fastTurnaroundDesc: 'Efficient production cycles with 15-30 day delivery timelines. Rush order capabilities and flexible scheduling to meet urgent deadlines without compromising quality.',
    yearsExp: 'Years Experience',
    countriesServ: 'Countries Served',
    happyClients: 'Happy Clients',
    qualityRate: 'Quality Rate',
    viewProducts: 'View Products',
    // Hero Section Content
    heroTitle1: 'Premium Hoodies Collection',
    heroSubtitle1: 'Ultimate Comfort Meets Style',
    heroDesc1: 'Crafted with premium materials and attention to detail, our hoodies blend streetwear aesthetics with unmatched comfort for the modern lifestyle.',
    heroTitle2: 'Elite Sportswear Manufacturing',
    heroSubtitle2: 'Performance-Driven Athletic Apparel',
    heroDesc2: 'Engineered for champions with moisture-wicking technology, breathable fabrics, and ergonomic designs that enhance athletic performance.',
    heroTitle3: 'Classic T-Shirt Excellence',
    heroSubtitle3: 'Timeless Style, Perfect Fit',
    heroDesc3: 'From premium cotton basics to designer cuts, our t-shirts represent the perfect fusion of comfort, durability, and contemporary fashion.',
    heroTitle4: 'Varsity Jacket Heritage',
    heroSubtitle4: 'Collegiate Style Redefined',
    heroDesc4: 'Authentic varsity craftsmanship with modern materials and designs that celebrate tradition while embracing contemporary streetwear culture.',
    heroTitle5: 'Luxury Leather Jackets',
    heroSubtitle5: 'Timeless Elegance & Sophistication',
    heroDesc5: 'Meticulously crafted from premium genuine leather, our jackets embody luxury, durability, and classic style that transcends seasons.',
    heroTitle6: 'Peak Fitness Apparel',
    heroSubtitle6: 'Activate Your Potential',
    heroDesc6: 'High-performance fitness wear designed with cutting-edge fabric technology to support your most intense workouts and active lifestyle.',
    heroTitle7: 'Cozy Sweatshirt Collection',
    heroSubtitle7: 'Relaxed Luxury for Everyday',
    heroDesc7: 'Soft, warm, and stylish sweatshirts that provide the perfect balance of comfort and fashion for casual and athleisure wear.',
    heroTitle8: 'Premium Shorts Range',
    heroSubtitle8: 'Freedom of Movement & Style',
    heroDesc8: 'From athletic performance to casual comfort, our shorts collection offers versatile designs with superior materials and modern fits.',
    whyChooseTitleStart: 'Why Axiom Rise Apparel Is Among One Of The Leading',
    whyChooseTitleHighlight: 'Clothing Manufacturer',
    guaranteedQualityTitle: 'Guaranteed Quality Products',
    guaranteedQualityDesc: 'We take quality seriously at Axiom Rise Apparel. All of our products are made using the best materials and are rigorously tested to ensure they meet our high standards.',
    lowMoqTitle: 'Low MOQ, Zero Inventory Risk',
    lowMoqDesc: 'We understand that inventory risk can be a concern for our clients, which is why we offer a low minimum order quantity. This means you can order exactly what you need without worrying about excess inventory.',
    customStylesTitle: 'Exquisite Custom Styles',
    customStylesDesc: 'Our team of experienced designers and craftsmen work closely with you to create custom clothing that perfectly represents your brand and vision, ensuring every piece is unique and exceptional.',
    creativeDesignsTitle: 'Creative And Unique Designs',
    creativeDesignsDesc: 'Our design team is committed to creating innovative and unique designs that will make your brand stand out. We&apos;re constantly pushing the boundaries to create something truly special.',
    endlessCustomizationTitle: 'Endless Customization Options',
    endlessCustomizationDesc: 'We offer a vast array of customization options to choose from. Whether it\'s the material, color, or design, we can help you create the perfect product for your brand.',
    ctaTitle: 'Ready to Partner with Us?',
    ctaDesc: 'Join thousands of satisfied clients worldwide. Get in touch today for competitive pricing and exceptional service.',
    ctaButton: 'Contact Us Today',
    // About Page translations
    aboutHeroBadge: 'About Axiom Rise',
    aboutHeroTitle: 'A clothing manufacturer you can rely on',
    aboutHeroDesc: 'We help apparel brands bring ideas to market with dependable production, agile sourcing, and a product-first mindset. From design development to bulk manufacturing, our team delivers quality garments with speed and care.',
    aboutHeroImageAlt: 'Premium hoodies manufacturing',
    aboutHeroCardTitle: 'Trusted production partner',
    aboutHeroCardDesc: 'Streamlined workflows, transparent timelines, and consistent quality across every order.',
    aboutStatsRnD: 'R&D specialists',
    aboutStatsCapacity: 'Monthly capacity',
    aboutStatsLeadTime: 'Lead time',
    aboutStatsCountries: 'Countries served',
    aboutStoryTitle: 'The story behind Axiom Rise',
    aboutStoryP1: 'Axiom Rise was founded by a team of apparel professionals with decades of experience in sourcing, product development, and production. Our goal was to build a reliable manufacturing partner for growing brands worldwide.',
    aboutStoryP2: 'Today we support labels of all sizes with fast sampling, clear communication, and scalable production. From boutique launches to global rollouts, we help customers create garments that sell.',
    aboutStoryP3: 'We continue to expand our capabilities with modern machinery, expert teams, and a dedicated R&D function that keeps our clients ahead of the curve.',
    aboutStoryImageAlt: 'Apparel design and development',
    aboutStoryCardTitle: 'Fast turnaround',
    aboutStoryCardDesc: 'Sampling and bulk timelines built for modern fashion cycles.',
    aboutValuesTitle: 'Our values',
    aboutValuesDesc: 'The principles that guide every fabric choice, stitch, and shipment.',
    aboutValue1Title: 'Quality First',
    aboutValue1Desc: 'We combine premium materials, skilled craftsmanship, and modern production controls to deliver consistent, durable apparel.',
    aboutValue2Title: 'Client Success',
    aboutValue2Desc: 'Your goals shape our process. We prioritize clear communication, fast iteration, and on-time delivery for every order.',
    aboutValue3Title: 'Responsible Growth',
    aboutValue3Desc: 'We invest in ethical sourcing, efficient production, and long-term partnerships that support people and the planet.',
    aboutCapabilitiesTitle: 'Development capabilities built for speed',
    aboutCapabilitiesDesc: 'Our in-house development center turns concepts into production-ready styles. With experienced designers and production specialists, we help you validate fit, fabric, and finish before scaling.',
    aboutCapability1: '20+ apparel designers and production specialists',
    aboutCapability2: '100+ new styles developed per month',
    aboutCapability3: 'Flexible MOQ options for growing brands',
    aboutCapability4: 'On-trend development across casualwear, activewear, and uniforms',
    aboutCapability5: 'Sampling support to validate fit and finish',
    aboutCapabilitiesImageAlt1: 'Apparel planning and tech packs',
    aboutCapabilitiesImageAlt2: 'Sampling and fit checks',
    aboutCapabilitiesImageAlt3: 'Production workflow',
    aboutCapabilitiesImageAlt4: 'Quality assurance and delivery readiness',
    aboutServicesTitle: 'Our services',
    aboutServicesDesc: 'End-to-end manufacturing support for apparel businesses.',
    aboutService1Title: 'Cut & Sew',
    aboutService1Desc: 'From patterns to final stitch, we build your apparel line with precise sizing, trims, and finishes.',
    aboutService2Title: 'Private Label',
    aboutService2Desc: 'Launch and scale your brand with custom labels, tags, packaging, and brand-aligned finishing.',
    aboutService3Title: 'OEM Production',
    aboutService3Desc: 'Produce to spec with tailored materials, construction methods, and performance requirements.',
    aboutSustainabilityTitle: 'Our commitment to sustainability',
    aboutSustainabilityP1: 'We build apparel with responsibility in mind. Our sourcing options include organic and recycled materials, and we prioritize efficient production methods that reduce waste.',
    aboutSustainabilityP2: 'Ethical labor practices and transparent supply chains are central to how we operate. We work closely with partners who share our commitment to people and the planet.',
    aboutSustainabilityImageAlt: 'Sustainable and quality-focused apparel',
    aboutSustainabilityCardTitle: 'Sustainability commitment',
    aboutSustainabilityCardDesc: 'Organic, recycled, and responsible fabrics with ethical labor practices.',
    aboutCTAHeading: 'Ready to build your next collection?',
    aboutCTADesc: 'Tell us about your apparel needs and we will help you plan the right production path.',
    aboutCTAButton: 'Get in touch',
    // Footer translations
    footerCompanyDesc: 'Leading clothing export company specializing in high-quality garments for global markets. We deliver excellence in every thread.',
    footerQuickLinks: 'Quick Links',
    footerAboutUs: 'About Us',
    footerProducts: 'Products',
    footerServices: 'Services',
    footerContact: 'Contact',
    footerContactInfo: 'Contact Info',
    footerAddress1: 'Kotla Amba Wala Road, Sialkot',
    footerAddress2: 'Sialkot, Punjab 51310',
    footerCountry: 'Pakistan',
    footerPhone: '+92 327 1213923',
    footerEmail: 'info@axiomrise.co',
    footerCopyright: '© 2025 Axiom Rise. All rights reserved.',
    footerLogoAlt: 'Axiom Rise Logo',
    footerFacebook: 'Facebook',
    footerInstagram: 'Instagram',
    footerLinkedIn: 'LinkedIn',
    // Product Categories Section translations
    productCategoriesBadge: 'Our Products',
    productCategoriesTitle: 'Our Product Categories',
    productCategoriesDesc: 'Discover our diverse range of high-quality clothing for various markets',
    productCategoriesReadMore: 'READ MORE',
    productCategoriesExploreMore: 'EXPLORE MORE PRODUCTS',
    // Products Hero Section translations
    productsHeroTitle: 'Our Products',
    productsHeroDesc: 'Explore our comprehensive range of high-quality clothing and textile products manufactured with precision and care',
    // Products CTA Section translations
    productsCTATitle: 'Can\'t Find What You\'re Looking For?',
    productsCTADesc: 'We offer custom manufacturing solutions tailored to your specific needs. Contact us to discuss your requirements',
    productsCTAContactUs: 'Contact Us',
    productsCTAViewServices: 'View Our Services',
    // Products Grid translations
    productsGridSearchPlaceholder: 'Search products...',
    productsGridShowingProducts: 'Showing',
    productsGridProducts: 'products',
    productsGridLearnMore: 'Learn More',
    productsGridGetQuote: 'Get Quote',
    productsGridNoProductsFound: 'No Products Found',
    productsGridNoProductsDesc: 'Try adjusting your search or filter criteria',
    productsGridClearFilters: 'Clear Filters',
    productsGridCategoryAll: 'All',
    productsGridCategoryJackets: 'Jackets',
    productsGridCategoryHoodies: 'Hoodies',
    productsGridCategoryTShirts: 'T-Shirts',
    productsGridCategorySportswear: 'Sportswear',
    productsGridCategoryUniforms: 'Uniforms',
    productsGridCategoryAccessories: 'Accessories',
    // Services Hero Section translations
    servicesHeroTitle: 'Our Services',
    servicesHeroDesc: 'Comprehensive clothing export solutions tailored to your specific business needs, delivering exceptional results every time',
    // Services Grid translations
    servicesGridTitle: 'What We Offer',
    servicesGridDesc: 'From manufacturing to global delivery, we provide end-to-end solutions',
    servicesManufacturingTitle: 'Manufacturing Excellence',
    servicesManufacturingDesc: 'State-of-the-art manufacturing facilities equipped with modern machinery and skilled workforce',
    servicesManufacturingFeature1: 'Advanced cutting and sewing equipment',
    servicesManufacturingFeature2: 'Quality control at every stage',
    servicesManufacturingFeature3: 'Skilled craftsmen and technicians',
    servicesManufacturingFeature4: 'Flexible production capacity',
    servicesCustomDesignTitle: 'Custom Design & Development',
    servicesCustomDesignDesc: 'Transform your ideas into reality with our comprehensive design and development services',
    servicesCustomDesignFeature1: 'Pattern making and grading',
    servicesCustomDesignFeature2: 'Sample development',
    servicesCustomDesignFeature3: 'Design consultation',
    servicesCustomDesignFeature4: 'Trend analysis and forecasting',
    servicesGlobalExportTitle: 'Global Export Services',
    servicesGlobalExportDesc: 'Seamless export solutions to deliver your products anywhere in the world',
    servicesGlobalExportFeature1: 'International shipping coordination',
    servicesGlobalExportFeature2: 'Customs clearance assistance',
    servicesGlobalExportFeature3: 'Documentation support',
    servicesGlobalExportFeature4: 'Tracking and logistics management',
    servicesQualityTitle: 'Quality Assurance',
    servicesQualityDesc: 'Comprehensive quality control processes ensuring products meet international standards',
    servicesQualityFeature1: 'Pre-production quality planning',
    servicesQualityFeature2: 'In-line quality monitoring',
    servicesQualityFeature3: 'Final inspection protocols',
    servicesQualityFeature4: 'Compliance certifications',
    servicesPrivateLabelTitle: 'Private Label Solutions',
    servicesPrivateLabelDesc: 'Complete private label services from concept to delivery',
    servicesPrivateLabelFeature1: 'Brand development support',
    servicesPrivateLabelFeature2: 'Custom packaging design',
    servicesPrivateLabelFeature3: 'Label and tag production',
    servicesPrivateLabelFeature4: 'Exclusive product lines',
    servicesSupplyChainTitle: 'Supply Chain Management',
    servicesSupplyChainDesc: 'End-to-end supply chain solutions for maximum efficiency and cost-effectiveness',
    servicesSupplyChainFeature1: 'Raw material sourcing',
    servicesSupplyChainFeature2: 'Inventory management',
    servicesSupplyChainFeature3: 'Production planning',
    servicesSupplyChainFeature4: 'Delivery scheduling',
    // Process Section translations
    processSectionTitle: 'Our Process',
    processSectionDesc: 'A streamlined approach ensuring quality and efficiency at every step',
    processConsultationTitle: 'Consultation',
    processConsultationDesc: 'Initial discussion to understand your requirements and specifications',
    processDesignPlanningTitle: 'Design & Planning',
    processDesignPlanningDesc: 'Create detailed designs and production timeline based on your needs',
    processSampleDevelopmentTitle: 'Sample Development',
    processSampleDevelopmentDesc: 'Develop and refine samples until they meet your exact requirements',
    processProductionTitle: 'Production',
    processProductionDesc: 'Begin full-scale production with continuous quality monitoring',
    processQualityControlTitle: 'Quality Control',
    processQualityControlDesc: 'Comprehensive quality checks before packaging and shipping',
    processDeliveryTitle: 'Delivery',
    processDeliveryDesc: 'Secure packaging and timely delivery to your specified destination',
    productWhyChoosePrefix: 'Why Axiom Rise is Your Perfect Choice for a',
    productUltimateSolutionPrefix: 'Ultimate Solution for Custom',
    productOrderStepsPrefix: 'Simple Steps to Ordering High Quality',
    // Services CTA Section translations
    servicesCTAReadyToGetStarted: 'Ready to Get Started?',
    servicesCTAContactDesc: 'Contact our team today to discuss your project requirements and discover how we can help bring your vision to life',
    servicesCTARequestQuote: 'Request Quote',
    servicesCTAScheduleConsultation: 'Schedule Consultation',
    // Contact Page translations
    contactHeroTitle: 'Contact Us',
    contactHeroDesc: 'Ready to partner with us? Get in touch today and discover how we can help your business grow',
    contactFormTitle: 'Send Us a Message',
    contactFormDesc: 'Fill out the form below and our team will get back to you within 24 hours.',
    contactFormFullName: 'Full Name *',
    contactFormEmail: 'Email Address *',
    contactFormCompany: 'Company Name',
    contactFormPhone: 'Phone Number',
    contactFormSubject: 'Subject *',
    contactFormMessage: 'Message *',
    contactFormFullNamePlaceholder: 'Your full name',
    contactFormEmailPlaceholder: 'your.email@example.com',
    contactFormCompanyPlaceholder: 'Your company name',
    contactFormPhonePlaceholder: '+1 (555) 123-4567',
    contactFormMessagePlaceholder: 'Please provide details about your inquiry...',
    contactFormSubjectSelect: 'Please select a subject',
    contactFormSubjectGeneral: 'General Inquiry',
    contactFormSubjectQuote: 'Request Quote',
    contactFormSubjectPartnership: 'Partnership Opportunity',
    contactFormSubjectQuality: 'Quality Concern',
    contactFormSubjectSupport: 'Technical Support',
    contactFormSubjectOther: 'Other',
    contactFormSendMessage: 'Send Message',
    contactInfoTitle: 'Get in Touch',
    contactInfoDesc: 'We\'re here to help! Reach out to us through any of the following channels.',
    contactInfoHeadOffice: 'Head Office',
    contactInfoPhoneFax: 'Phone & Fax',
    contactInfoEmail: 'Email',
    contactInfoBusinessHours: 'Business Hours',
    contactSocialTitle: 'Follow Us',
    contactSocialDesc: 'Stay connected with us on social media',
    contactMapTitle: 'Find Us',
    contactFAQTitle: 'Frequently Asked Questions',
    contactFAQDesc: 'Quick answers to common questions about our services',
    contactFAQ1Question: 'What is your minimum order quantity?',
    contactFAQ1Answer: 'Our minimum order quantity varies by product type. Generally, we require a minimum of 500 pieces per style for most garments. Contact us for specific requirements.',
    contactFAQ2Question: 'How long does production take?',
    contactFAQ2Answer: 'Production time typically ranges from 15-30 days depending on the complexity and quantity of the order. Rush orders may be accommodated with additional fees.',
    contactFAQ3Question: 'Do you provide samples?',
    contactFAQ3Answer: 'Yes, we provide samples for approval before production begins. Sample costs are typically deducted from the final order total.',
    contactFAQ4Question: 'What payment methods do you accept?',
    contactFAQ4Answer: 'We accept bank transfers, letters of credit, and other secure international payment methods. Payment terms are typically 30% deposit with 70% before shipment.',
    contactFAQ5Question: 'Can you handle custom designs?',
    contactFAQ5Answer: 'Absolutely! We specialize in custom designs and can work with your specifications, sketches, or even develop designs based on your requirements.',
    contactFAQ6Question: 'What quality certifications do you have?',
    contactFAQ6Answer: 'We hold ISO 9001:2015, OEKO-TEX Standard 100, GOTS certification, and BSCI compliance certifications ensuring highest quality and ethical standards.',
    // Blog Hero Section translations
    blogHeroTitle: 'Our Blog',
    blogHeroDesc: 'Insights, trends, and expert advice from the world of clothing manufacturing and textile exports',
    // Blog Categories translations
    blogCategoryAll: 'All',
    blogCategoryManufacturing: 'Manufacturing',
    blogCategorySustainability: 'Sustainability',
    blogCategoryFashionTrends: 'Fashion Trends',
    blogCategoryExportGuide: 'Export Guide',
    blogCategoryQualityControl: 'Quality Control',
    blogCategoryIndustryNews: 'Industry News',
    // Blog CTA Section translations
    blogCTAHeading: 'Stay Updated with Industry Insights',
    blogCTADescription: 'Subscribe to our newsletter and get the latest articles, trends, and manufacturing tips delivered to your inbox',
    blogCTAEmailPlaceholder: 'Enter your email address',
    blogCTASubscribeButton: 'Subscribe Now',
    blogCTASubscribersText: 'Join 5,000+ industry professionals already receiving our insights',
    blogCTASocialHeading: 'Follow us on social media',
    // Blog Grid translations
    blogGridShowingArticles: 'Showing',
    blogGridArticles: 'article',
    blogGridArticlesPlural: 'articles',
    blogGridInCategory: 'in',
    blogGridReadMore: 'Read More',
    blogGridNoArticlesFound: 'No Articles Found',
    blogGridNoArticlesMessage: 'No articles available in this category yet. Check back soon!',
    blogGridLoadMore: 'Load More Articles',
    // Blog Posts translations
    blogPost1Title: 'The Complete Guide to Starting Your Private Label Clothing Line',
    blogPost1Excerpt: 'Learn everything you need to know about launching your own private label clothing brand, from finding the right manufacturer to quality control.',
    blogPost2Title: 'Sustainable Manufacturing: The Future of Fashion Industry',
    blogPost2Excerpt: 'Discover how eco-friendly practices and sustainable materials are transforming the clothing manufacturing landscape.',
    blogPost3Title: 'Understanding Fabric Quality: A Buyer\'s Guide',
    blogPost3Excerpt: 'Everything you need to know about fabric types, quality grades, and how to choose the right materials for your clothing line.',
    blogPost4Title: 'Export Documentation: Essential Guide for Clothing Manufacturers',
    blogPost4Excerpt: 'Navigate the complex world of international trade with our comprehensive guide to export documentation and customs clearance.',
    blogPost5Title: 'Top 10 Fashion Trends Shaping 2025',
    blogPost5Excerpt: 'Stay ahead of the curve with our analysis of the biggest fashion trends and how they\'re influencing manufacturing demands.',
    blogPost6Title: 'Quality Control Checklist for Garment Manufacturing',
    blogPost6Excerpt: 'A detailed checklist to ensure your products meet international quality standards and exceed customer expectations.',
    blogPost7Title: 'How to Choose the Right Clothing Manufacturer for Your Brand',
    blogPost7Excerpt: 'Key factors to consider when selecting a manufacturing partner, from production capacity to communication and reliability.',
    blogPost8Title: 'The Rise of Athleisure: Manufacturing Opportunities',
    blogPost8Excerpt: 'Explore the booming athleisure market and how manufacturers can capitalize on this growing trend.',
    blogPost9Title: 'Understanding MOQ: Minimum Order Quantities Explained',
    blogPost9Excerpt: 'Learn about minimum order quantities, how they work, and strategies for negotiating better terms with manufacturers.'
  },
  de: {
    home: 'STARTSEITE',
    products: 'PRODUKTE',
    services: 'DIENSTLEISTUNGEN',
    clients: 'KUNDEN',
    blog: 'BLOG',
    about: 'ÜBER UNS',
    contact: 'KONTAKT',
    talkToExpert: 'KONTAKTIEREN SIE UNS',
    manufacturingBadge: 'Ihr Fertigungspartner',
    manufacturingTitleStart: 'Suchen Sie einen vertrauenswürdigen Partner in der Bekleidungsindustrie für Ihre',
    manufacturingTitleHighlight: 'perfekte Bekleidungsfertigung?',
    manufacturingDesc1Start: 'Mit unzähligen Bekleidungsproduzenten auf dem Markt kann die Suche nach dem richtigen Partner überwältigend und erschöpfend sein.',
    manufacturingDesc1Highlight: 'Aber Ihre Suche endet hier!',
    manufacturingDesc1End: 'Als eines der angesehensten und etabliertesten Bekleidungsfertigungsunternehmen bieten wir umfassende Lösungen für alle Ihre Bekleidungsproduktionsanforderungen.',
    manufacturingDesc2: 'Als Pionier innovativer Mode sind wir stolz darauf, Ihr ultimative Fertigungspartner zu sein und sicherzustellen, dass sich Ihre Marke auf dem heutigen wettbewerbsintensiven Markt durch unsere Premium-Bekleidungsfertigungsdienste auszeichnet. Als führender Bekleidungshersteller und Exporteur zeichnen wir uns durch die Lieferung von Produkten aus, die nicht nur internationale Qualitätsstandards erfüllen, sondern Erwartungen übertreffen und garantieren, dass Ihre Marke nichts weniger als außergewöhnliche Exzellenz erhält.',
    getQuote: 'ANGEBOT EINHOLEN',
    yearsExperience: 'Jahre Erfahrung',
    countriesServed: 'Bediente Länder',
    customBadge: 'Maßgeschneiderte Lösungen',
    customTitleStart: 'Maßgeschneiderte Bekleidungshersteller in Pakistan,',
    customTitleHighlight: 'Exklusive Bekleidung Herstellen',
    customDesc1: 'Wenn Sie nach einem maßgeschneiderten Bekleidungshersteller in Pakistan suchen, der alle Ihre einzigartigen Anforderungen erfüllen kann? Ihre Suche endet hier bei Rijiz, wo wir eine umfangreiche Palette maßgeschneiderter Bekleidungslösungen liefern, um Ihre Vision in die Realität umzusetzen. Im Gegensatz zu anderen Maßschneidern für Bekleidung bieten wir vollständige maßgeschneiderte Bekleidungsfertigungsdienste mit grenzenlosen Anpassungsmöglichkeiten.',
    customDesc2Start: 'Bei Rijiz sind wir stolz darauf, hochwertige Bekleidung zu produzieren, die genau Ihren Spezifikationen entspricht. Von Siebdruck und Stickerei bis hin zu Digitaldruck,',
    customDesc2Link: 'Private-Label-Bekleidungsfertigung',
    customDesc2End: ', Schneide- und Näh-Bekleidungsproduktion und maßgeschneidertem Design bieten wir eine umfassende Palette von Anpassungsdiensten, die in der Branche unübertroffen sind.',
    customDesigns: 'Maßgeschneiderte Designs',
    supportAvailable: 'Support Verfügbar',
    featuresBadge: 'Unsere Vorteile',
    featuresTitleStart: 'Warum Wählen',
    featuresTitleHighlight: 'Axiom Rise',
    featuresTitleEnd: '?',
    featuresDesc: 'Wir kombinieren traditionelles Handwerk mit modernster Technologie, um außergewöhnliche Bekleidungsprodukte zu liefern, die Erwartungen übertreffen und weltweit Industriestandards setzen.',
    premiumQualityTitle: 'Premium-Qualitätssicherung',
    premiumQualityDesc: 'Jedes Kleidungsstück durchläuft strenge mehrstufige Qualitätskontrollprozesse mit ISO 9001:2015-Zertifizierung, die die Einhaltung internationaler Standards und eine fehlerfreie Lieferung gewährleisten.',
    globalExportTitle: 'Globales Exportnetzwerk',
    globalExportDesc: 'Erfolgreich exportierend in über 50 Länder in Nordamerika, Europa, Asien und darüber hinaus mit etablierten Logistikpartnerschaften und Zollkenntnissen.',
    expertTeamTitle: 'Experten-Fertigungsteam',
    expertTeamDesc: 'Über 5 Jahre Branchenerfahrung mit qualifizierten Handwerkern und modernen Produktionsanlagen, ausgestattet mit modernster Technologie für präzise Fertigung.',
    sustainableTitle: 'Nachhaltig & Ethisch',
    sustainableDesc: 'OEKO-TEX-zertifizierte umweltfreundliche Materialien mit GOTS-Bio-Baumwolloptionen. BSCI-konforme ethische Arbeitspraktiken und umweltverantwortliche Produktion.',
    customDesignTitle: 'Maßgeschneiderte Designlösungen',
    customDesignDesc: 'In-house-Designteam, das vollständige Anpassung von Konzept bis Produktion anbietet. Tech Packs, Musterentwicklung und Private-Label-Fertigungsdienste.',
    fastTurnaroundTitle: 'Schnelle Bearbeitungszeit',
    fastTurnaroundDesc: 'Effiziente Produktionszyklen mit 15-30 Tagen Lieferzeiten. Eilauftragsmöglichkeiten und flexible Terminplanung, um dringende Fristen ohne Qualitätsverlust zu erfüllen.',
    yearsExp: 'Jahre Erfahrung',
    countriesServ: 'Bediente Länder',
    happyClients: 'Zufriedene Kunden',
    qualityRate: 'Qualitätsrate',
    viewProducts: 'Produkte Ansehen',
    // Hero Section Content
    heroTitle1: 'Premium Hoodies Kollektion',
    heroSubtitle1: 'Ultimativer Komfort Trifft Stil',
    heroDesc1: 'Hergestellt mit Premium-Materialien und Liebe zum Detail, vereinen unsere Hoodies Streetwear-Ästhetik mit unübertroffenem Komfort für den modernen Lebensstil.',
    heroTitle2: 'Elite Sportbekleidung Fertigung',
    heroSubtitle2: 'Leistungsorientierte Athletische Bekleidung',
    heroDesc2: 'Entwickelt für Champions mit Feuchtigkeitsableitender Technologie, atmungsaktiven Stoffen und ergonomischen Designs, die die sportliche Leistung verbessern.',
    heroTitle3: 'Klassische T-Shirt Exzellenz',
    heroSubtitle3: 'Zeitloser Stil, Perfekter Sitz',
    heroDesc3: 'Von Premium-Baumwoll-Basics bis hin zu Designer-Schnitten repräsentieren unsere T-Shirts die perfekte Fusion aus Komfort, Haltbarkeit und zeitgenössischer Mode.',
    heroTitle4: 'Varsity Jackett Erbe',
    heroSubtitle4: 'Hochschulstil Neu Definiert',
    heroDesc4: 'Authentische Varsity Handwerkskunst mit modernen Materialien und Designs, die Tradition feiern und gleichzeitig die zeitgenössische Streetwear-Kultur umarmen.',
    heroTitle5: 'Luxus Lederjacken',
    heroSubtitle5: 'Zeitlose Eleganz & Raffinesse',
    heroDesc5: 'Sorgfältig aus echtem Premium-Leder gefertigt, verkörpern unsere Jacken Luxus, Haltbarkeit und klassischen Stil, der Jahreszeiten überdauert.',
    heroTitle6: 'Spitzen Fitness Bekleidung',
    heroSubtitle6: 'Aktiviere Dein Potenzial',
    heroDesc6: 'Hochleistungs-Fitnessbekleidung, entwickelt mit modernster Stofftechnologie, um Ihre intensivsten Workouts und Ihren aktiven Lebensstil zu unterstützen.',
    heroTitle7: 'Gemütliche Sweatshirt Kollektion',
    heroSubtitle7: 'Entspannte Luxus für Den Alltag',
    heroDesc7: 'Weiche, warme und stilvolle Sweatshirts, die das perfekte Gleichgewicht zwischen Komfort und Mode für Freizeit- und Athleisure-Mode bieten.',
    heroTitle8: 'Premium Shorts Sortiment',
    heroSubtitle8: 'Freiheit Der Bewegung & Stil',
    heroDesc8: 'Von athletischer Leistung bis hin zu lässigem Komfort bietet unsere Shorts-Kollektion vielseitige Designs mit überlegenen Materialien und modernen Schnitten.',
    whyChooseTitleStart: 'Warum Axiom Rise Apparel Zu Einer Der Führenden Gehört',
    whyChooseTitleHighlight: 'Bekleidungshersteller',
    guaranteedQualityTitle: 'Garantierte Qualitätsprodukte',
    guaranteedQualityDesc: 'Wir nehmen Qualität bei Axiom Rise Apparel ernst. Alle unsere Produkte werden aus den besten Materialien hergestellt und rigoros getestet, um sicherzustellen, dass sie unsere hohen Standards erfüllen.',
    lowMoqTitle: 'Niedrige MOQ, Null Lagerbestandsrisiko',
    lowMoqDesc: 'Wir verstehen, dass Lagerbestandsrisiko ein Anliegen für unsere Kunden sein kann, weshalb wir eine niedrige Mindestbestellmenge anbieten. Das bedeutet, Sie können genau das bestellen, was Sie brauchen, ohne sich Sorgen um überschüssigen Lagerbestand machen zu müssen.',
    customStylesTitle: 'Erlesene Maßgeschneiderte Stile',
    customStylesDesc: 'Unser Team erfahrener Designer und Handwerker arbeitet eng mit Ihnen zusammen, um maßgeschneiderte Bekleidung zu schaffen, die Ihre Marke und Vision perfekt repräsentiert und sicherstellt, dass jedes Stück einzigartig und außergewöhnlich ist.',
    creativeDesignsTitle: 'Kreative Und Einzigartige Designs',
    creativeDesignsDesc: 'Unser Designteam ist verpflichtet, innovative und einzigartige Designs zu schaffen, die Ihre Marke hervorstechen lassen. Wir stoßen ständig an Grenzen, um etwas wirklich Besonderes zu schaffen.',
    endlessCustomizationTitle: 'Endlose Anpassungsoptionen',
    endlessCustomizationDesc: 'Wir bieten eine Vielzahl von Anpassungsoptionen zur Auswahl. Ob Material, Farbe oder Design, wir können Ihnen helfen, das perfekte Produkt für Ihre Marke zu schaffen.',
    ctaTitle: 'Bereit, mit uns zu partnern?',
    ctaDesc: 'Treten Sie Tausenden zufriedenen Kunden weltweit bei. Kontaktieren Sie uns heute für wettbewerbsfähige Preise und außergewöhnlichen Service.',
    ctaButton: 'Kontaktieren Sie uns heute',
    // About Page translations
    aboutHeroBadge: 'Über Axiom Rise',
    aboutHeroTitle: 'Ein Bekleidungshersteller, auf den Sie sich verlassen können',
    aboutHeroDesc: 'Wir helfen Bekleidungsmarken, Ideen mit zuverlässiger Produktion, agiler Beschaffung und einem produktorientierten Ansatz auf den Markt zu bringen. Von der Entwicklung bis zur Serienfertigung liefert unser Team hochwertige Kleidung schnell und sorgfältig.',
    aboutHeroImageAlt: 'Premium-Hoodie-Fertigung',
    aboutHeroCardTitle: 'Verlässlicher Produktionspartner',
    aboutHeroCardDesc: 'Optimierte Abläufe, transparente Zeitpläne und gleichbleibende Qualität bei jeder Bestellung.',
    aboutStatsRnD: 'F&E-Spezialisten',
    aboutStatsCapacity: 'Monatliche Kapazität',
    aboutStatsLeadTime: 'Lieferzeit',
    aboutStatsCountries: 'Belieferte Länder',
    aboutStoryTitle: 'Die Geschichte hinter Axiom Rise',
    aboutStoryP1: 'Axiom Rise wurde von einem Team aus Bekleidungsprofis mit jahrzehntelanger Erfahrung in Beschaffung, Produktentwicklung und Produktion gegründet. Unser Ziel war es, ein verlässlicher Fertigungspartner für wachsende Marken weltweit zu sein.',
    aboutStoryP2: 'Heute unterstützen wir Labels jeder Größe mit schneller Musterung, klarer Kommunikation und skalierbarer Produktion. Von Boutique-Launches bis zu globalen Rollouts helfen wir, Produkte zu entwickeln, die sich verkaufen.',
    aboutStoryP3: 'Wir erweitern unsere Fähigkeiten kontinuierlich mit moderner Ausstattung, Expertenteams und einer dedizierten F&E-Funktion, die unsere Kunden stets einen Schritt voraus hält.',
    aboutStoryImageAlt: 'Bekleidungsdesign und -entwicklung',
    aboutStoryCardTitle: 'Schnelle Durchlaufzeit',
    aboutStoryCardDesc: 'Muster- und Serienzeitpläne, die moderne Modezyklen unterstützen.',
    aboutValuesTitle: 'Unsere Werte',
    aboutValuesDesc: 'Prinzipien, die jede Stoffwahl, Naht und Lieferung leiten.',
    aboutValue1Title: 'Qualität zuerst',
    aboutValue1Desc: 'Wir verbinden Premium-Materialien, handwerkliches Können und moderne Produktionskontrollen für konsistente, langlebige Bekleidung.',
    aboutValue2Title: 'Kundenerfolg',
    aboutValue2Desc: 'Ihre Ziele bestimmen unseren Prozess. Wir priorisieren klare Kommunikation, schnelle Iteration und pünktliche Lieferung bei jeder Bestellung.',
    aboutValue3Title: 'Verantwortungsvolles Wachstum',
    aboutValue3Desc: 'Wir investieren in ethische Beschaffung, effiziente Produktion und langfristige Partnerschaften, die Menschen und Umwelt unterstützen.',
    aboutCapabilitiesTitle: 'Entwicklungskompetenzen für Geschwindigkeit',
    aboutCapabilitiesDesc: 'Unser internes Entwicklungszentrum macht Konzepte produktionsreif. Mit erfahrenen Designern und Produktionsexperten helfen wir, Passform, Stoff und Finish vor der Skalierung zu validieren.',
    aboutCapability1: '20+ Bekleidungsdesigner und Produktionsexperten',
    aboutCapability2: '100+ neue Styles pro Monat',
    aboutCapability3: 'Flexible MOQ-Optionen für wachsende Marken',
    aboutCapability4: 'Trendnahe Entwicklung für Casualwear, Activewear und Uniformen',
    aboutCapability5: 'Musterunterstützung zur Validierung von Passform und Finish',
    aboutCapabilitiesImageAlt1: 'Bekleidungsplanung und Tech Packs',
    aboutCapabilitiesImageAlt2: 'Musterung und Passform-Checks',
    aboutCapabilitiesImageAlt3: 'Produktionsablauf',
    aboutCapabilitiesImageAlt4: 'Qualitätssicherung und Versandbereitschaft',
    aboutServicesTitle: 'Unsere Leistungen',
    aboutServicesDesc: 'End-to-End-Fertigungsunterstützung für Bekleidungsunternehmen.',
    aboutService1Title: 'Cut & Sew',
    aboutService1Desc: 'Von Schnittmustern bis zur letzten Naht fertigen wir Ihre Kollektion mit präzisen Größen, Details und Abschlüssen.',
    aboutService2Title: 'Private Label',
    aboutService2Desc: 'Skalieren Sie Ihre Marke mit individuellen Labels, Tags, Verpackungen und markenkonformen Veredelungen.',
    aboutService3Title: 'OEM-Produktion',
    aboutService3Desc: 'Produktion nach Spezifikation mit maßgeschneiderten Materialien, Konstruktionen und Leistungsanforderungen.',
    aboutSustainabilityTitle: 'Unser Engagement für Nachhaltigkeit',
    aboutSustainabilityP1: 'Wir fertigen Bekleidung verantwortungsbewusst. Unsere Beschaffung umfasst organische und recycelte Materialien, und wir priorisieren effiziente Produktionsmethoden zur Abfallreduzierung.',
    aboutSustainabilityP2: 'Ethische Arbeitspraktiken und transparente Lieferketten stehen im Mittelpunkt unseres Handelns. Wir arbeiten mit Partnern zusammen, die unser Engagement für Mensch und Umwelt teilen.',
    aboutSustainabilityImageAlt: 'Nachhaltige und qualitätsorientierte Bekleidung',
    aboutSustainabilityCardTitle: 'Nachhaltigkeitsversprechen',
    aboutSustainabilityCardDesc: 'Organische, recycelte und verantwortungsvolle Stoffe mit ethischen Arbeitspraktiken.',
    aboutCTAHeading: 'Bereit, Ihre nächste Kollektion zu realisieren?',
    aboutCTADesc: 'Erzählen Sie uns von Ihren Bekleidungsanforderungen, und wir helfen Ihnen, den richtigen Produktionsweg zu planen.',
    aboutCTAButton: 'Kontakt aufnehmen',
    // Footer translations
    footerCompanyDesc: 'Führendes Bekleidungsexportunternehmen, spezialisiert auf hochwertige Kleidung für globale Märkte. Wir liefern Exzellenz in jedem Faden.',
    footerQuickLinks: 'Schnelllinks',
    footerAboutUs: 'Über uns',
    footerProducts: 'Produkte',
    footerServices: 'Dienstleistungen',
    footerContact: 'Kontakt',
    footerContactInfo: 'Kontaktinformationen',
    footerAddress1: 'Kotla Amba Wala Road, Sialkot',
    footerAddress2: 'Sialkot, Punjab 51310',
    footerCountry: 'Pakistan',
    footerPhone: '+92 327 1213923',
    footerEmail: 'info@axiomrise.co',
    footerCopyright: '© 2025 Axiom Rise. Alle Rechte vorbehalten.',
    footerLogoAlt: 'Axiom Rise Logo',
    footerFacebook: 'Facebook',
    footerInstagram: 'Instagram',
    footerLinkedIn: 'LinkedIn',
    // Product Categories Section translations
    productCategoriesBadge: 'Unsere Produkte',
    productCategoriesTitle: 'Unsere Produktkategorien',
    productCategoriesDesc: 'Entdecken Sie unsere vielfältige Palette hochwertiger Kleidung für verschiedene Märkte',
    productCategoriesReadMore: 'WEITERLESEN',
    productCategoriesExploreMore: 'MEHR PRODUKTE ENTDECKEN',
    // Products Hero Section translations
    productsHeroTitle: 'Unsere Produkte',
    productsHeroDesc: 'Entdecken Sie unser umfassendes Sortiment an hochwertiger Bekleidung und Textilprodukten, die mit Präzision und Sorgfalt hergestellt werden',
    // Products CTA Section translations
    productsCTATitle: 'Können Sie nicht finden, wonach Sie suchen?',
    productsCTADesc: 'Wir bieten maßgeschneiderte Fertigungslösungen, die auf Ihre spezifischen Bedürfnisse zugeschnitten sind. Kontaktieren Sie uns, um Ihre Anforderungen zu besprechen',
    productsCTAContactUs: 'Kontaktieren Sie uns',
    productsCTAViewServices: 'Unsere Dienstleistungen ansehen',
    // Products Grid translations
    productsGridSearchPlaceholder: 'Produkte suchen...',
    productsGridShowingProducts: 'Zeige',
    productsGridProducts: 'Produkte',
    productsGridLearnMore: 'Mehr erfahren',
    productsGridGetQuote: 'Angebot erhalten',
    productsGridNoProductsFound: 'Keine Produkte gefunden',
    productsGridNoProductsDesc: 'Versuchen Sie, Ihre Such- oder Filterkriterien anzupassen',
    productsGridClearFilters: 'Filter löschen',
    productsGridCategoryAll: 'Alle',
    productsGridCategoryJackets: 'Jacken',
    productsGridCategoryHoodies: 'Hoodies',
    productsGridCategoryTShirts: 'T-Shirts',
    productsGridCategorySportswear: 'Sportbekleidung',
    productsGridCategoryUniforms: 'Uniformen',
    productsGridCategoryAccessories: 'Zubehör',
    // Services Hero Section translations
    servicesHeroTitle: 'Unsere Dienstleistungen',
    servicesHeroDesc: 'Umfassende Bekleidungsexportlösungen, die auf Ihre spezifischen Geschäftsanforderungen zugeschnitten sind und jedes Mal außergewöhnliche Ergebnisse liefern',
    // Services Grid translations
    servicesGridTitle: 'Was Wir Bieten',
    servicesGridDesc: 'Von der Fertigung bis zur weltweiten Lieferung bieten wir End-to-End-Lösungen',
    servicesManufacturingTitle: 'Fertigungsexzellenz',
    servicesManufacturingDesc: 'Hochmoderne Fertigungseinrichtungen ausgestattet mit modernen Maschinen und qualifiziertem Personal',
    servicesManufacturingFeature1: 'Fortgeschrittene Schneide- und Nähmaschinen',
    servicesManufacturingFeature2: 'Qualitätskontrolle in jeder Phase',
    servicesManufacturingFeature3: 'Qualifizierte Handwerker und Techniker',
    servicesManufacturingFeature4: 'Flexible Produktionskapazität',
    servicesCustomDesignTitle: 'Maßgeschneiderte Design & Entwicklung',
    servicesCustomDesignDesc: 'Verwandeln Sie Ihre Ideen in Realität mit unseren umfassenden Design- und Entwicklungsdiensten',
    servicesCustomDesignFeature1: 'Schnitterstellung und Gradierung',
    servicesCustomDesignFeature2: 'Musterentwicklung',
    servicesCustomDesignFeature3: 'Designberatung',
    servicesCustomDesignFeature4: 'Trendanalyse und Prognose',
    servicesGlobalExportTitle: 'Globale Exportdienstleistungen',
    servicesGlobalExportDesc: 'Nahtlose Exportlösungen, um Ihre Produkte überall auf der Welt zu liefern',
    servicesGlobalExportFeature1: 'Internationale Versandkoordination',
    servicesGlobalExportFeature2: 'Zollabfertigungshilfe',
    servicesGlobalExportFeature3: 'Dokumentationsunterstützung',
    servicesGlobalExportFeature4: 'Verfolgung und Logistikmanagement',
    servicesQualityTitle: 'Qualitätssicherung',
    servicesQualityDesc: 'Umfassende Qualitätskontrollprozesse, die sicherstellen, dass Produkte internationale Standards erfüllen',
    servicesQualityFeature1: 'Qualitätsplanung vor der Produktion',
    servicesQualityFeature2: 'Inline-Qualitätsüberwachung',
    servicesQualityFeature3: 'Endkontrollprotokolle',
    servicesQualityFeature4: 'Compliance-Zertifizierungen',
    servicesPrivateLabelTitle: 'Private Label Lösungen',
    servicesPrivateLabelDesc: 'Vollständige Private-Label-Dienstleistungen vom Konzept bis zur Lieferung',
    servicesPrivateLabelFeature1: 'Markenentwicklungsunterstützung',
    servicesPrivateLabelFeature2: 'Maßgeschneiderte Verpackungsgestaltung',
    servicesPrivateLabelFeature3: 'Etiketten- und Anhängerproduktion',
    servicesPrivateLabelFeature4: 'Exklusive Produktlinien',
    servicesSupplyChainTitle: 'Lieferkettenmanagement',
    servicesSupplyChainDesc: 'End-to-End-Lieferkettenlösungen für maximale Effizienz und Kosteneffektivität',
    servicesSupplyChainFeature1: 'Rohstoffbeschaffung',
    servicesSupplyChainFeature2: 'Bestandsverwaltung',
    servicesSupplyChainFeature3: 'Produktionsplanung',
    servicesSupplyChainFeature4: 'Lieferplanung',
    // Process Section translations
    processSectionTitle: 'Unser Prozess',
    processSectionDesc: 'Ein optimierter Ansatz, der Qualität und Effizienz in jedem Schritt gewährleistet',
    processConsultationTitle: 'Beratung',
    processConsultationDesc: 'Erstgespräch, um Ihre Anforderungen und Spezifikationen zu verstehen',
    processDesignPlanningTitle: 'Design & Planung',
    processDesignPlanningDesc: 'Erstellen Sie detaillierte Designs und Produktionszeitpläne basierend auf Ihren Bedürfnissen',
    processSampleDevelopmentTitle: 'Musterentwicklung',
    processSampleDevelopmentDesc: 'Entwickeln und verfeinern Sie Muster, bis sie Ihren genauen Anforderungen entsprechen',
    processProductionTitle: 'Produktion',
    processProductionDesc: 'Beginnen Sie die Großserienproduktion mit kontinuierlicher Qualitätsüberwachung',
    processQualityControlTitle: 'Qualitätskontrolle',
    processQualityControlDesc: 'Umfassende Qualitätsprüfungen vor Verpackung und Versand',
    processDeliveryTitle: 'Lieferung',
    processDeliveryDesc: 'Sichere Verpackung und termingerechte Lieferung an Ihr angegebenes Ziel',
    productWhyChoosePrefix: 'Warum Axiom Rise die perfekte Wahl für',
    productUltimateSolutionPrefix: 'Ultimative Lösung für maßgeschneiderte',
    productOrderStepsPrefix: 'Einfache Schritte zur Bestellung von hochwertigen',
    // Services CTA Section translations
    servicesCTAReadyToGetStarted: 'Bereit zu Beginnen?',
    servicesCTAContactDesc: 'Kontaktieren Sie unser Team heute, um Ihre Projektanforderungen zu besprechen und zu entdecken, wie wir Ihnen helfen können, Ihre Vision zum Leben zu erwecken',
    servicesCTARequestQuote: 'Angebot Anfordern',
    servicesCTAScheduleConsultation: 'Beratung Vereinbaren',
    // Contact Page translations
    contactHeroTitle: 'Kontaktieren Sie uns',
    contactHeroDesc: 'Bereit für eine Partnerschaft mit uns? Kontaktieren Sie uns heute und entdecken Sie, wie wir Ihrem Unternehmen helfen können zu wachsen',
    contactFormTitle: 'Senden Sie uns eine Nachricht',
    contactFormDesc: 'Füllen Sie das untenstehende Formular aus und unser Team wird sich innerhalb von 24 Stunden bei Ihnen melden.',
    contactFormFullName: 'Vollständiger Name *',
    contactFormEmail: 'E-Mail-Adresse *',
    contactFormCompany: 'Firmenname',
    contactFormPhone: 'Telefonnummer',
    contactFormSubject: 'Betreff *',
    contactFormMessage: 'Nachricht *',
    contactFormFullNamePlaceholder: 'Ihr vollständiger Name',
    contactFormEmailPlaceholder: 'ihre.email@beispiel.com',
    contactFormCompanyPlaceholder: 'Ihr Firmenname',
    contactFormPhonePlaceholder: '+49 (123) 456-7890',
    contactFormMessagePlaceholder: 'Bitte geben Sie Details zu Ihrer Anfrage an...',
    contactFormSubjectSelect: 'Bitte wählen Sie einen Betreff',
    contactFormSubjectGeneral: 'Allgemeine Anfrage',
    contactFormSubjectQuote: 'Angebot anfordern',
    contactFormSubjectPartnership: 'Partnerschaftsmöglichkeit',
    contactFormSubjectQuality: 'Qualitätsbedenken',
    contactFormSubjectSupport: 'Technischer Support',
    contactFormSubjectOther: 'Sonstiges',
    contactFormSendMessage: 'Nachricht senden',
    contactInfoTitle: 'Nehmen Sie Kontakt auf',
    contactInfoDesc: 'Wir sind hier, um zu helfen! Kontaktieren Sie uns über einen der folgenden Kanäle.',
    contactInfoHeadOffice: 'Hauptsitz',
    contactInfoPhoneFax: 'Telefon & Fax',
    contactInfoEmail: 'E-Mail',
    contactInfoBusinessHours: 'Geschäftszeiten',
    contactSocialTitle: 'Folgen Sie uns',
    contactSocialDesc: 'Bleiben Sie mit uns in den sozialen Medien verbunden',
    contactMapTitle: 'Finden Sie uns',
    contactFAQTitle: 'Häufig gestellte Fragen',
    contactFAQDesc: 'Schnelle Antworten auf häufige Fragen zu unseren Dienstleistungen',
    contactFAQ1Question: 'Was ist Ihre Mindestbestellmenge?',
    contactFAQ1Answer: 'Unsere Mindestbestellmenge variiert je nach Produkttyp. Im Allgemeinen benötigen wir ein Minimum von 500 Stück pro Stil für die meisten Kleidungsstücke. Kontaktieren Sie uns für spezifische Anforderungen.',
    contactFAQ2Question: 'Wie lange dauert die Produktion?',
    contactFAQ2Answer: 'Die Produktionszeit liegt typischerweise zwischen 15-30 Tagen, abhängig von der Komplexität und Menge der Bestellung. Eilaufträge können mit zusätzlichen Gebühren untergebracht werden.',
    contactFAQ3Question: 'Bieten Sie Muster an?',
    contactFAQ3Answer: 'Ja, wir bieten Muster zur Genehmigung an, bevor die Produktion beginnt. Musterkosten werden typischerweise vom Gesamtauftrag abgezogen.',
    contactFAQ4Question: 'Welche Zahlungsmethoden akzeptieren Sie?',
    contactFAQ4Answer: 'Wir akzeptieren Banküberweisungen, Akkreditive und andere sichere internationale Zahlungsmethoden. Zahlungsbedingungen sind typischerweise 30% Anzahlung mit 70% vor Versand.',
    contactFAQ5Question: 'Können Sie maßgeschneiderte Designs handhaben?',
    contactFAQ5Answer: 'Absolut! Wir spezialisieren uns auf maßgeschneiderte Designs und können mit Ihren Spezifikationen, Skizzen oder sogar Designs basierend auf Ihren Anforderungen entwickeln.',
    contactFAQ6Question: 'Welche Qualitätszertifizierungen haben Sie?',
    contactFAQ6Answer: 'Wir halten ISO 9001:2015, OEKO-TEX Standard 100, GOTS-Zertifizierung und BSCI-Compliance-Zertifizierungen, die höchste Qualität und ethische Standards gewährleisten.',
    // Blog Hero Section translations
    blogHeroTitle: 'Unser Blog',
    blogHeroDesc: 'Einblicke, Trends und Expertenratschläge aus der Welt der Bekleidungsfertigung und Textilienexporte',
    // Blog Categories translations
    blogCategoryAll: 'Alle',
    blogCategoryManufacturing: 'Fertigung',
    blogCategorySustainability: 'Nachhaltigkeit',
    blogCategoryFashionTrends: 'Mode-Trends',
    blogCategoryExportGuide: 'Export-Leitfaden',
    blogCategoryQualityControl: 'Qualitätskontrolle',
    blogCategoryIndustryNews: 'Branchen-News',
    // Blog CTA Section translations
    blogCTAHeading: 'Bleiben Sie mit Brancheneinblicken auf dem Laufenden',
    blogCTADescription: 'Abonnieren Sie unseren Newsletter und erhalten Sie die neuesten Artikel, Trends und Fertigungstipps direkt in Ihren Posteingang',
    blogCTAEmailPlaceholder: 'Geben Sie Ihre E-Mail-Adresse ein',
    blogCTASubscribeButton: 'Jetzt abonnieren',
    blogCTASubscribersText: 'Treten Sie 5.000+ Branchenprofis bei, die bereits unsere Einblicke erhalten',
    blogCTASocialHeading: 'Folgen Sie uns in den sozialen Medien',
    // Blog Grid translations
    blogGridShowingArticles: 'Zeige',
    blogGridArticles: 'Artikel',
    blogGridArticlesPlural: 'Artikel',
    blogGridInCategory: 'in',
    blogGridReadMore: 'Weiterlesen',
    blogGridNoArticlesFound: 'Keine Artikel gefunden',
    blogGridNoArticlesMessage: 'Noch keine Artikel in dieser Kategorie verfügbar. Schauen Sie bald wieder vorbei!',
    blogGridLoadMore: 'Mehr Artikel laden',
    // Blog Posts translations
    blogPost1Title: 'Der vollständige Leitfaden zum Starten Ihrer Private-Label-Bekleidungslinie',
    blogPost1Excerpt: 'Erfahren Sie alles, was Sie wissen müssen, um Ihre eigene Private-Label-Bekleidungsmarke zu starten, von der Suche nach dem richtigen Hersteller bis zur Qualitätskontrolle.',
    blogPost2Title: 'Nachhaltige Fertigung: Die Zukunft der Modeindustrie',
    blogPost2Excerpt: 'Entdecken Sie, wie umweltfreundliche Praktiken und nachhaltige Materialien die Bekleidungsfertigungslandschaft verändern.',
    blogPost3Title: 'Stoffqualität verstehen: Ein Käuferleitfaden',
    blogPost3Excerpt: 'Alles, was Sie über Stoffarten, Qualitätsstufen und die Auswahl der richtigen Materialien für Ihre Bekleidungslinie wissen müssen.',
    blogPost4Title: 'Exportdokumentation: Wesentlicher Leitfaden für Bekleidungshersteller',
    blogPost4Excerpt: 'Navigieren Sie durch die komplexe Welt des internationalen Handels mit unserem umfassenden Leitfaden zur Exportdokumentation und Zollabfertigung.',
    blogPost5Title: 'Top 10 Modetrends, die 2025 prägen',
    blogPost5Excerpt: 'Bleiben Sie der Konkurrenz voraus mit unserer Analyse der größten Modetrends und wie sie die Fertigungsnachfrage beeinflussen.',
    blogPost6Title: 'Qualitätskontroll-Checkliste für Bekleidungsfertigung',
    blogPost6Excerpt: 'Eine detaillierte Checkliste, um sicherzustellen, dass Ihre Produkte internationale Qualitätsstandards erfüllen und Kundenerwartungen übertreffen.',
    blogPost7Title: 'Wie man den richtigen Bekleidungshersteller für Ihre Marke auswählt',
    blogPost7Excerpt: 'Wichtige Faktoren, die bei der Auswahl eines Fertigungspartners zu berücksichtigen sind, von der Produktionskapazität bis zur Kommunikation und Zuverlässigkeit.',
    blogPost8Title: 'Der Aufstieg von Athleisure: Fertigungsmöglichkeiten',
    blogPost8Excerpt: 'Erkunden Sie den boomenden Athleisure-Markt und wie Hersteller diesen wachsenden Trend nutzen können.',
    blogPost9Title: 'MOQ verstehen: Mindestbestellmengen erklärt',
    blogPost9Excerpt: 'Erfahren Sie mehr über Mindestbestellmengen, wie sie funktionieren und Strategien für bessere Verhandlungskonditionen mit Herstellern.'
  },
  es: {
    home: 'INICIO',
    products: 'PRODUCTOS',
    services: 'SERVICIOS',
    clients: 'CLIENTES',
    blog: 'BLOG',
    about: 'SOBRE NOSOTROS',
    contact: 'CONTACTO',
    talkToExpert: 'CONTÁCTENOS',
    manufacturingBadge: 'Su Socio de Manufactura',
    manufacturingTitleStart: '¿Está Buscando un Socio de Confianza en la Industria de la Ropa para Su',
    manufacturingTitleHighlight: 'Manufactura Perfecta de Ropa?',
    manufacturingDesc1Start: 'Con innumerables productores de ropa en el mercado, encontrar el socio adecuado puede ser abrumador y agotador.',
    manufacturingDesc1Highlight: '¡Pero su búsqueda termina aquí!',
    manufacturingDesc1End: 'Como una de las compañías de manufactura de ropa más reputadas y establecidas, proporcionamos soluciones integrales para todos sus requisitos de producción de ropa.',
    manufacturingDesc2: 'Como pionero de la moda innovadora, nos enorgullecemos de ser su socio de manufactura definitivo, asegurando que su marca se distinga en el mercado competitivo actual a través de nuestros servicios premium de manufactura de ropa. Como fabricante y exportador líder de ropa, sobresalimos en la entrega de productos que no solo cumplen con los estándares de calidad internacionales, sino que superan las expectativas, garantizando que su marca reciba nada menos que excelencia excepcional.',
    getQuote: 'OBTENER PRESUPUESTO',
    yearsExperience: 'Años de Experiencia',
    countriesServed: 'Países Atendidos',
    customBadge: 'Soluciones Personalizadas',
    customTitleStart: 'Fabricantes de Ropa Personalizada en Pakistán,',
    customTitleHighlight: 'Fabricando Ropa Exclusiva',
    customDesc1: '¿Está buscando un fabricante de ropa personalizada en Pakistán que pueda satisfacer todas sus necesidades únicas? Su búsqueda termina aquí en Rijiz, donde entregamos una amplia gama de soluciones de ropa personalizada para transformar su visión en realidad. A diferencia de otros fabricantes de ropa a medida, proporcionamos servicios completos de manufactura de ropa personalizada con posibilidades de personalización ilimitadas.',
    customDesc2Start: 'En Rijiz, nos enorgullecemos de producir ropa de calidad premium que se alinea con sus especificaciones exactas. Desde serigrafía y bordado hasta impresión digital,',
    customDesc2Link: 'manufactura de ropa de marca privada',
    customDesc2End: ', producción de ropa cortada y cosida, y diseño personalizado, presentamos una amplia gama de servicios de personalización que son incomparables en la industria.',
    customDesigns: 'Diseños Personalizados',
    supportAvailable: 'Soporte Disponible',
    featuresBadge: 'Nuestras Ventajas',
    featuresTitleStart: '¿Por Qué Elegir',
    featuresTitleHighlight: 'Axiom Rise',
    featuresTitleEnd: '?',
    featuresDesc: 'Combinamos el artesanado tradicional con la tecnología de vanguardia para entregar productos de ropa excepcionales que superan las expectativas y establecen estándares de la industria en todo el mundo.',
    premiumQualityTitle: 'Garantía de Calidad Premium',
    premiumQualityDesc: 'Cada prenda pasa por rigurosos procesos de control de calidad en múltiples etapas con certificación ISO 9001:2015, asegurando el cumplimiento de estándares internacionales y entrega sin defectos.',
    globalExportTitle: 'Red de Exportación Global',
    globalExportDesc: 'Exportando exitosamente a más de 50 países en Norteamérica, Europa, Asia y más allá con asociaciones logísticas establecidas y experiencia aduanera.',
    expertTeamTitle: 'Equipo de Manufactura Experto',
    expertTeamDesc: 'Más de 5 años de experiencia en la industria con artesanos calificados y instalaciones de producción modernas equipadas con tecnología de vanguardia para manufactura de precisión.',
    sustainableTitle: 'Sostenible y Ético',
    sustainableDesc: 'Materiales ecológicos certificados OEKO-TEX con opciones de algodón orgánico GOTS. Prácticas laborales éticas conformes con BSCI y producción responsable con el medio ambiente.',
    customDesignTitle: 'Soluciones de Diseño Personalizado',
    customDesignDesc: 'Equipo de diseño interno que ofrece personalización completa desde el concepto hasta la producción. Paquetes técnicos, desarrollo de muestras y servicios de manufactura de marca privada.',
    fastTurnaroundTitle: 'Tiempo de Entrega Rápido',
    fastTurnaroundDesc: 'Ciclos de producción eficientes con plazos de entrega de 15-30 días. Capacidades de pedidos urgentes y programación flexible para cumplir con plazos urgentes sin comprometer la calidad.',
    yearsExp: 'Años de Experiencia',
    countriesServ: 'Países Atendidos',
    happyClients: 'Clientes Satisfechos',
    qualityRate: 'Tasa de Calidad',
    viewProducts: 'Ver Productos',
    // Hero Section Content
    heroTitle1: 'Colección Premium de Hoodies',
    heroSubtitle1: 'Comodidad Definitiva Se Encuentra con Estilo',
    heroDesc1: 'Elaborados con materiales premium y atención al detalle, nuestros hoodies combinan la estética streetwear con comodidad incomparable para el estilo de vida moderno.',
    heroTitle2: 'Fabricación Elite de Ropa Deportiva',
    heroSubtitle2: 'Ropa Atlética Impulsada por Rendimiento',
    heroDesc2: 'Ingenierizada para campeones con tecnología de absorción de humedad, telas transpirables y diseños ergonómicos que mejoran el rendimiento atlético.',
    heroTitle3: 'Excelencia Clásica en Camisetas',
    heroSubtitle3: 'Estilo Atemporal, Ajuste Perfecto',
    heroDesc3: 'Desde básicos de algodón premium hasta cortes de diseñador, nuestras camisetas representan la fusión perfecta de comodidad, durabilidad y moda contemporánea.',
    heroTitle4: 'Herencia de Chaquetas Varsity',
    heroSubtitle4: 'Estilo Universitario Redefinido',
    heroDesc4: 'Artesanía varsity auténtica con materiales y diseños modernos que celebran la tradición mientras abrazan la cultura streetwear contemporánea.',
    heroTitle5: 'Chaquetas de Cuero de Lujo',
    heroSubtitle5: 'Elegancia & Sofisticación Atemporal',
    heroDesc5: 'Meticulosamente elaboradas con cuero genuino premium, nuestras chaquetas encarnan lujo, durabilidad y estilo clásico que trasciende las estaciones.',
    heroTitle6: 'Ropa de Fitness de Punta',
    heroSubtitle6: 'Activa Tu Potencial',
    heroDesc6: 'Ropa de fitness de alto rendimiento diseñada con tecnología avanzada de telas para apoyar tus entrenamientos más intensos y estilo de vida activo.',
    heroTitle7: 'Colección Acogedora de Sudaderas',
    heroSubtitle7: 'Lujo Relajado para Todos los Días',
    heroDesc7: 'Sudaderas suaves, cálidas y elegantes que proporcionan el equilibrio perfecto entre comodidad y moda para uso casual y athleisure.',
    heroTitle8: 'Gama Premium de Shorts',
    heroSubtitle8: 'Libertad de Movimiento & Estilo',
    heroDesc8: 'Desde rendimiento atlético hasta comodidad casual, nuestra colección de shorts ofrece diseños versátiles con materiales superiores y ajustes modernos.',
    whyChooseTitleStart: '¿Por Qué Axiom Rise Apparel Está Entre Uno De Los Principales',
    whyChooseTitleHighlight: 'Fabricantes de Ropa',
    guaranteedQualityTitle: 'Productos de Calidad Garantizada',
    guaranteedQualityDesc: 'Tomamos la calidad en serio en Axiom Rise Apparel. Todos nuestros productos están hechos con los mejores materiales y son rigurosamente probados para asegurar que cumplan con nuestros altos estándares.',
    lowMoqTitle: 'MOQ Bajo, Riesgo de Inventario Cero',
    lowMoqDesc: 'Entendemos que el riesgo de inventario puede ser una preocupación para nuestros clientes, por eso ofrecemos una cantidad mínima de pedido baja. Esto significa que puede ordenar exactamente lo que necesita sin preocuparse por el exceso de inventario.',
    customStylesTitle: 'Estilos Personalizados Exquisitos',
    customStylesDesc: 'Nuestro equipo de diseñadores y artesanos experimentados trabaja estrechamente con usted para crear ropa personalizada que represente perfectamente su marca y visión, asegurando que cada pieza sea única y excepcional.',
    creativeDesignsTitle: 'Diseños Creativos y Únicos',
    creativeDesignsDesc: 'Nuestro equipo de diseño está comprometido a crear diseños innovadores y únicos que harán que su marca se destaque. Estamos constantemente empujando los límites para crear algo verdaderamente especial.',
    endlessCustomizationTitle: 'Opciones de Personalización Infinitas',
    endlessCustomizationDesc: 'Ofrecemos una amplia gama de opciones de personalización para elegir. Ya sea el material, color o diseño, podemos ayudarle a crear el producto perfecto para su marca.',
    ctaTitle: '¿Listo para asociarse con nosotros?',
    ctaDesc: 'Únase a miles de clientes satisfechos en todo el mundo. Póngase en contacto hoy para precios competitivos y servicio excepcional.',
    ctaButton: 'Contáctenos hoy',
    // About Page translations
    aboutHeroBadge: 'Sobre Axiom Rise',
    aboutHeroTitle: 'Un fabricante de ropa en el que puede confiar',
    aboutHeroDesc: 'Ayudamos a las marcas de apparel a llevar ideas al mercado con producción confiable, abastecimiento ágil y un enfoque centrado en el producto. Desde el desarrollo de diseño hasta la fabricación a gran escala, nuestro equipo entrega prendas de calidad con rapidez y cuidado.',
    aboutHeroImageAlt: 'Fabricación de hoodies premium',
    aboutHeroCardTitle: 'Socio de producción confiable',
    aboutHeroCardDesc: 'Flujos de trabajo ágiles, plazos transparentes y calidad constante en cada pedido.',
    aboutStatsRnD: 'Especialistas de I+D',
    aboutStatsCapacity: 'Capacidad mensual',
    aboutStatsLeadTime: 'Tiempo de entrega',
    aboutStatsCountries: 'Países atendidos',
    aboutStoryTitle: 'La historia detrás de Axiom Rise',
    aboutStoryP1: 'Axiom Rise fue fundada por un equipo de profesionales del apparel con décadas de experiencia en abastecimiento, desarrollo de producto y producción. Nuestro objetivo era construir un socio de manufactura confiable para marcas en crecimiento en todo el mundo.',
    aboutStoryP2: 'Hoy apoyamos marcas de todos los tamaños con muestreo rápido, comunicación clara y producción escalable. Desde lanzamientos boutique hasta expansiones globales, ayudamos a crear prendas que se venden.',
    aboutStoryP3: 'Seguimos ampliando nuestras capacidades con maquinaria moderna, equipos expertos y una función dedicada de I+D que mantiene a nuestros clientes a la vanguardia.',
    aboutStoryImageAlt: 'Diseño y desarrollo de prendas',
    aboutStoryCardTitle: 'Respuesta rápida',
    aboutStoryCardDesc: 'Cronogramas de muestreo y producción pensados para ciclos de moda modernos.',
    aboutValuesTitle: 'Nuestros valores',
    aboutValuesDesc: 'Los principios que guían cada elección de tela, puntada y envío.',
    aboutValue1Title: 'Calidad primero',
    aboutValue1Desc: 'Combinamos materiales premium, artesanía experta y controles modernos de producción para ofrecer prendas consistentes y duraderas.',
    aboutValue2Title: 'Éxito del cliente',
    aboutValue2Desc: 'Sus objetivos dan forma a nuestro proceso. Priorizamos comunicación clara, iteraciones rápidas y entregas puntuales en cada pedido.',
    aboutValue3Title: 'Crecimiento responsable',
    aboutValue3Desc: 'Invertimos en abastecimiento ético, producción eficiente y alianzas de largo plazo que apoyan a las personas y al planeta.',
    aboutCapabilitiesTitle: 'Capacidades de desarrollo diseñadas para la velocidad',
    aboutCapabilitiesDesc: 'Nuestro centro interno de desarrollo convierte conceptos en estilos listos para producción. Con diseñadores y especialistas en producción, le ayudamos a validar ajuste, tela y acabado antes de escalar.',
    aboutCapability1: '20+ diseñadores y especialistas en producción',
    aboutCapability2: '100+ nuevos estilos desarrollados por mes',
    aboutCapability3: 'Opciones flexibles de MOQ para marcas en crecimiento',
    aboutCapability4: 'Desarrollo en tendencia para casual, activewear y uniformes',
    aboutCapability5: 'Soporte de muestreo para validar ajuste y acabado',
    aboutCapabilitiesImageAlt1: 'Planificación de apparel y tech packs',
    aboutCapabilitiesImageAlt2: 'Muestreo y pruebas de ajuste',
    aboutCapabilitiesImageAlt3: 'Flujo de trabajo de producción',
    aboutCapabilitiesImageAlt4: 'Aseguramiento de calidad y preparación de entrega',
    aboutServicesTitle: 'Nuestros servicios',
    aboutServicesDesc: 'Soporte integral de manufactura para negocios de apparel.',
    aboutService1Title: 'Cut & Sew',
    aboutService1Desc: 'Desde los patrones hasta la última puntada, construimos su línea con tallaje, detalles y acabados precisos.',
    aboutService2Title: 'Marca privada',
    aboutService2Desc: 'Lance y escale su marca con etiquetas, tags, empaque y acabados alineados con su identidad.',
    aboutService3Title: 'Producción OEM',
    aboutService3Desc: 'Producción según especificaciones con materiales, métodos de confección y requisitos de rendimiento a medida.',
    aboutSustainabilityTitle: 'Nuestro compromiso con la sostenibilidad',
    aboutSustainabilityP1: 'Fabricamos prendas con responsabilidad. Nuestras opciones de abastecimiento incluyen materiales orgánicos y reciclados, y priorizamos métodos de producción eficientes que reducen residuos.',
    aboutSustainabilityP2: 'Las prácticas laborales éticas y las cadenas de suministro transparentes son centrales en nuestra operación. Trabajamos con socios que comparten nuestro compromiso con las personas y el planeta.',
    aboutSustainabilityImageAlt: 'Apparel sostenible y orientado a la calidad',
    aboutSustainabilityCardTitle: 'Compromiso con la sostenibilidad',
    aboutSustainabilityCardDesc: 'Tejidos orgánicos, reciclados y responsables con prácticas laborales éticas.',
    aboutCTAHeading: '¿Listo para crear su próxima colección?',
    aboutCTADesc: 'Cuéntenos sus necesidades de apparel y le ayudaremos a planificar el camino de producción adecuado.',
    aboutCTAButton: 'Contáctenos',
    // Footer translations
    footerCompanyDesc: 'Empresa líder en exportación de ropa especializada en prendas de alta calidad para mercados globales. Entregamos excelencia en cada hilo.',
    footerQuickLinks: 'Enlaces Rápidos',
    footerAboutUs: 'Sobre Nosotros',
    footerProducts: 'Productos',
    footerServices: 'Servicios',
    footerContact: 'Contacto',
    footerContactInfo: 'Información de Contacto',
    footerAddress1: 'Kotla Amba Wala Road, Sialkot',
    footerAddress2: 'Sialkot, Punjab 51310',
    footerCountry: 'Pakistán',
    footerPhone: '+92 327 1213923',
    footerEmail: 'info@axiomrise.co',
    footerCopyright: '© 2025 Axiom Rise. Todos los derechos reservados.',
    footerLogoAlt: 'Logo de Axiom Rise',
    footerFacebook: 'Facebook',
    footerInstagram: 'Instagram',
    footerLinkedIn: 'LinkedIn',
    // Product Categories Section translations
    productCategoriesBadge: 'Nuestros Productos',
    productCategoriesTitle: 'Nuestras Categorías de Productos',
    productCategoriesDesc: 'Descubre nuestra diversa gama de ropa de alta calidad para diversos mercados',
    productCategoriesReadMore: 'LEER MÁS',
    productCategoriesExploreMore: 'EXPLORAR MÁS PRODUCTOS',
    // Products Hero Section translations
    productsHeroTitle: 'Nuestros Productos',
    productsHeroDesc: 'Explore nuestra amplia gama de productos de ropa y textiles de alta calidad fabricados con precisión y cuidado',
    // Products CTA Section translations
    productsCTATitle: '¿No puede encontrar lo que busca?',
    productsCTADesc: 'Ofrecemos soluciones de fabricación personalizadas adaptadas a sus necesidades específicas. Contáctenos para discutir sus requisitos',
    productsCTAContactUs: 'Contáctenos',
    productsCTAViewServices: 'Ver nuestros servicios',
    // Products Grid translations
    productsGridSearchPlaceholder: 'Buscar productos...',
    productsGridShowingProducts: 'Mostrando',
    productsGridProducts: 'productos',
    productsGridLearnMore: 'Saber más',
    productsGridGetQuote: 'Obtener presupuesto',
    productsGridNoProductsFound: 'No se encontraron productos',
    productsGridNoProductsDesc: 'Intente ajustar su búsqueda o criterios de filtro',
    productsGridClearFilters: 'Limpiar filtros',
    productsGridCategoryAll: 'Todos',
    productsGridCategoryJackets: 'Chaquetas',
    productsGridCategoryHoodies: 'Sudaderas',
    productsGridCategoryTShirts: 'Camisetas',
    productsGridCategorySportswear: 'Ropa deportiva',
    productsGridCategoryUniforms: 'Uniformes',
    productsGridCategoryAccessories: 'Accesorios',
    // Services Hero Section translations
    servicesHeroTitle: 'Nuestros Servicios',
    servicesHeroDesc: 'Soluciones integrales de exportación de ropa diseñadas para satisfacer sus necesidades específicas de negocio y entregar resultados excepcionales cada vez',
    // Services Grid translations
    servicesGridTitle: 'Lo Que Ofrecemos',
    servicesGridDesc: 'Desde la manufactura hasta la entrega global, proporcionamos soluciones integrales',
    servicesManufacturingTitle: 'Excelencia en Manufactura',
    servicesManufacturingDesc: 'Instalaciones de manufactura de vanguardia equipadas con maquinaria moderna y mano de obra calificada',
    servicesManufacturingFeature1: 'Equipo avanzado de corte y costura',
    servicesManufacturingFeature2: 'Control de calidad en cada etapa',
    servicesManufacturingFeature3: 'Artesanos y técnicos calificados',
    servicesManufacturingFeature4: 'Capacidad de producción flexible',
    servicesCustomDesignTitle: 'Diseño Personalizado y Desarrollo',
    servicesCustomDesignDesc: 'Transforme sus ideas en realidad con nuestros servicios integrales de diseño y desarrollo',
    servicesCustomDesignFeature1: 'Creación de patrones y graduación',
    servicesCustomDesignFeature2: 'Desarrollo de muestras',
    servicesCustomDesignFeature3: 'Consulta de diseño',
    servicesCustomDesignFeature4: 'Análisis de tendencias y pronósticos',
    servicesGlobalExportTitle: 'Servicios de Exportación Global',
    servicesGlobalExportDesc: 'Soluciones de exportación perfectas para entregar sus productos en cualquier lugar del mundo',
    servicesGlobalExportFeature1: 'Coordinación de envío internacional',
    servicesGlobalExportFeature2: 'Asistencia en despacho aduanero',
    servicesGlobalExportFeature3: 'Soporte de documentación',
    servicesGlobalExportFeature4: 'Seguimiento y gestión logística',
    servicesQualityTitle: 'Garantía de Calidad',
    servicesQualityDesc: 'Procesos integrales de control de calidad que garantizan que los productos cumplan con estándares internacionales',
    servicesQualityFeature1: 'Planificación de calidad previa a la producción',
    servicesQualityFeature2: 'Monitoreo de calidad en línea',
    servicesQualityFeature3: 'Protocolos de inspección final',
    servicesQualityFeature4: 'Certificaciones de cumplimiento',
    servicesPrivateLabelTitle: 'Soluciones de Marca Privada',
    servicesPrivateLabelDesc: 'Servicios completos de marca privada desde el concepto hasta la entrega',
    servicesPrivateLabelFeature1: 'Soporte de desarrollo de marca',
    servicesPrivateLabelFeature2: 'Diseño de empaque personalizado',
    servicesPrivateLabelFeature3: 'Producción de etiquetas y tags',
    servicesPrivateLabelFeature4: 'Líneas de productos exclusivas',
    servicesSupplyChainTitle: 'Gestión de Cadena de Suministro',
    servicesSupplyChainDesc: 'Soluciones integrales de cadena de suministro para máxima eficiencia y rentabilidad',
    servicesSupplyChainFeature1: 'Adquisición de materias primas',
    servicesSupplyChainFeature2: 'Gestión de inventario',
    servicesSupplyChainFeature3: 'Planificación de producción',
    servicesSupplyChainFeature4: 'Programación de entregas',
    // Process Section translations
    processSectionTitle: 'Nuestro Proceso',
    processSectionDesc: 'Un enfoque optimizado que garantiza calidad y eficiencia en cada paso',
    processConsultationTitle: 'Consulta',
    processConsultationDesc: 'Discusión inicial para entender sus requisitos y especificaciones',
    processDesignPlanningTitle: 'Diseño y Planificación',
    processDesignPlanningDesc: 'Crear diseños detallados y cronograma de producción basado en sus necesidades',
    processSampleDevelopmentTitle: 'Desarrollo de Muestras',
    processSampleDevelopmentDesc: 'Desarrollar y refinar muestras hasta que cumplan con sus requisitos exactos',
    processProductionTitle: 'Producción',
    processProductionDesc: 'Comenzar la producción a gran escala con monitoreo continuo de calidad',
    processQualityControlTitle: 'Control de Calidad',
    processQualityControlDesc: 'Verificaciones integrales de calidad antes del empaque y envío',
    processDeliveryTitle: 'Entrega',
    processDeliveryDesc: 'Empaque seguro y entrega oportuna a su destino especificado',
    productWhyChoosePrefix: 'Por qué Axiom Rise es la elección perfecta para',
    productUltimateSolutionPrefix: 'Solución definitiva para',
    productOrderStepsPrefix: 'Pasos simples para ordenar',
    // Services CTA Section translations
    servicesCTAReadyToGetStarted: '¿Listo para Comenzar?',
    servicesCTAContactDesc: 'Contacte a nuestro equipo hoy para discutir los requisitos de su proyecto y descubrir cómo podemos ayudar a dar vida a su visión',
    servicesCTARequestQuote: 'Solicitar Presupuesto',
    servicesCTAScheduleConsultation: 'Programar Consulta',
    // Contact Page translations
    contactHeroTitle: 'Contáctenos',
    contactHeroDesc: '¿Listo para asociarse con nosotros? Póngase en contacto hoy y descubra cómo podemos ayudar a que su negocio crezca',
    contactFormTitle: 'Envíenos un mensaje',
    contactFormDesc: 'Complete el formulario a continuación y nuestro equipo se pondrá en contacto con usted dentro de 24 horas.',
    contactFormFullName: 'Nombre completo *',
    contactFormEmail: 'Dirección de correo electrónico *',
    contactFormCompany: 'Nombre de la empresa',
    contactFormPhone: 'Número de teléfono',
    contactFormSubject: 'Asunto *',
    contactFormMessage: 'Mensaje *',
    contactFormFullNamePlaceholder: 'Su nombre completo',
    contactFormEmailPlaceholder: 'su.correo@ejemplo.com',
    contactFormCompanyPlaceholder: 'Nombre de su empresa',
    contactFormPhonePlaceholder: '+1 (555) 123-4567',
    contactFormMessagePlaceholder: 'Por favor proporcione detalles sobre su consulta...',
    contactFormSubjectSelect: 'Por favor seleccione un asunto',
    contactFormSubjectGeneral: 'Consulta general',
    contactFormSubjectQuote: 'Solicitar presupuesto',
    contactFormSubjectPartnership: 'Oportunidad de asociación',
    contactFormSubjectQuality: 'Preocupación de calidad',
    contactFormSubjectSupport: 'Soporte técnico',
    contactFormSubjectOther: 'Otro',
    contactFormSendMessage: 'Enviar mensaje',
    contactInfoTitle: 'Póngase en contacto',
    contactInfoDesc: '¡Estamos aquí para ayudar! Comuníquese con nosotros a través de cualquiera de los siguientes canales.',
    contactInfoHeadOffice: 'Oficina principal',
    contactInfoPhoneFax: 'Teléfono y fax',
    contactInfoEmail: 'Correo electrónico',
    contactInfoBusinessHours: 'Horario comercial',
    contactSocialTitle: 'Síganos',
    contactSocialDesc: 'Manténgase conectado con nosotros en las redes sociales',
    contactMapTitle: 'Encuéntrenos',
    contactFAQTitle: 'Preguntas frecuentes',
    contactFAQDesc: 'Respuestas rápidas a preguntas comunes sobre nuestros servicios',
    contactFAQ1Question: '¿Cuál es su cantidad mínima de pedido?',
    contactFAQ1Answer: 'Nuestra cantidad mínima de pedido varía según el tipo de producto. Generalmente, requerimos un mínimo de 500 piezas por estilo para la mayoría de las prendas. Contáctenos para requisitos específicos.',
    contactFAQ2Question: '¿Cuánto tiempo toma la producción?',
    contactFAQ2Answer: 'El tiempo de producción generalmente oscila entre 15-30 días dependiendo de la complejidad y cantidad del pedido. Los pedidos urgentes pueden acomodarse con tarifas adicionales.',
    contactFAQ3Question: '¿Proporcionan muestras?',
    contactFAQ3Answer: 'Sí, proporcionamos muestras para aprobación antes de que comience la producción. Los costos de muestras generalmente se deducen del pedido total.',
    contactFAQ4Question: '¿Qué métodos de pago aceptan?',
    contactFAQ4Answer: 'Aceptamos transferencias bancarias, cartas de crédito y otros métodos de pago internacional seguros. Los términos de pago son típicamente 30% de depósito con 70% antes del envío.',
    contactFAQ5Question: '¿Pueden manejar diseños personalizados?',
    contactFAQ5Answer: '¡Absolutamente! Nos especializamos en diseños personalizados y podemos trabajar con sus especificaciones, bocetos o incluso desarrollar diseños basados en sus requisitos.',
    contactFAQ6Question: '¿Qué certificaciones de calidad tienen?',
    contactFAQ6Answer: 'Tenemos certificaciones ISO 9001:2015, OEKO-TEX Standard 100, certificación GOTS y certificaciones de cumplimiento BSCI que garantizan la más alta calidad y estándares éticos.',
    // Blog Hero Section translations
    blogHeroTitle: 'Nuestro Blog',
    blogHeroDesc: 'Perspectivas, tendencias y consejos de expertos del mundo de la fabricación de ropa y exportaciones textiles',
    // Blog Categories translations
    blogCategoryAll: 'Todos',
    blogCategoryManufacturing: 'Fabricación',
    blogCategorySustainability: 'Sostenibilidad',
    blogCategoryFashionTrends: 'Tendencias de Moda',
    blogCategoryExportGuide: 'Guía de Exportación',
    blogCategoryQualityControl: 'Control de Calidad',
    blogCategoryIndustryNews: 'Noticias de la Industria',
    // Blog CTA Section translations
    blogCTAHeading: 'Manténgase Actualizado con Perspectivas de la Industria',
    blogCTADescription: 'Suscríbase a nuestro boletín y reciba los últimos artículos, tendencias y consejos de fabricación directamente en su bandeja de entrada',
    blogCTAEmailPlaceholder: 'Ingrese su dirección de correo electrónico',
    blogCTASubscribeButton: 'Suscribirse Ahora',
    blogCTASubscribersText: 'Únase a 5,000+ profesionales de la industria que ya reciben nuestras perspectivas',
    blogCTASocialHeading: 'Síganos en las redes sociales',
    // Blog Grid translations
    blogGridShowingArticles: 'Mostrando',
    blogGridArticles: 'artículo',
    blogGridArticlesPlural: 'artículos',
    blogGridInCategory: 'en',
    blogGridReadMore: 'Leer más',
    blogGridNoArticlesFound: 'No se encontraron artículos',
    blogGridNoArticlesMessage: 'Aún no hay artículos disponibles en esta categoría. ¡Vuelva pronto!',
    blogGridLoadMore: 'Cargar más artículos',
    // Blog Posts translations
    blogPost1Title: 'La Guía Completa para Iniciar Su Línea de Ropa de Marca Privada',
    blogPost1Excerpt: 'Aprenda todo lo que necesita saber sobre lanzar su propia marca de ropa de etiqueta privada, desde encontrar el fabricante adecuado hasta el control de calidad.',
    blogPost2Title: 'Fabricación Sostenible: El Futuro de la Industria de la Moda',
    blogPost2Excerpt: 'Descubra cómo las prácticas ecológicas y los materiales sostenibles están transformando el panorama de la fabricación de ropa.',
    blogPost3Title: 'Entendiendo la Calidad de los Tejidos: Una Guía para Compradores',
    blogPost3Excerpt: 'Todo lo que necesita saber sobre tipos de tejidos, grados de calidad y cómo elegir los materiales adecuados para su línea de ropa.',
    blogPost4Title: 'Documentación de Exportación: Guía Esencial para Fabricantes de Ropa',
    blogPost4Excerpt: 'Navegue por el complejo mundo del comercio internacional con nuestra guía completa de documentación de exportación y despacho aduanero.',
    blogPost5Title: 'Top 10 Tendencias de Moda que Dan Forma a 2025',
    blogPost5Excerpt: 'Manténgase por delante de la curva con nuestro análisis de las tendencias de moda más grandes y cómo están influyendo en las demandas de fabricación.',
    blogPost6Title: 'Lista de Control de Calidad para Fabricación de Prendas',
    blogPost6Excerpt: 'Una lista de control detallada para asegurar que sus productos cumplan con estándares de calidad internacionales y superen las expectativas de los clientes.',
    blogPost7Title: 'Cómo Elegir el Fabricante de Ropa Adecuado para Su Marca',
    blogPost7Excerpt: 'Factores clave a considerar al seleccionar un socio de fabricación, desde la capacidad de producción hasta la comunicación y confiabilidad.',
    blogPost8Title: 'El Auge de Athleisure: Oportunidades de Fabricación',
    blogPost8Excerpt: 'Explore el mercado de athleisure en auge y cómo los fabricantes pueden capitalizar esta tendencia creciente.',
    blogPost9Title: 'Entendiendo MOQ: Cantidades Mínimas de Pedido Explicadas',
    blogPost9Excerpt: 'Aprenda sobre cantidades mínimas de pedido, cómo funcionan y estrategias para negociar mejores términos con los fabricantes.'
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    // Load language from localStorage on mount
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && ['en', 'de', 'es'].includes(savedLanguage)) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}